### ISSUE TITLE
Projections? Support? Samples

### ISSUE THREAD

**Issue by justinpenguin45** [unlight/nestjs-cqrx#6]
Any support for ES DB projections? Samples?

**Comment by unlight** [comment]
Sorry for being late.

1. I do not understand what you mean by "projections". In esdb, see https://developers.eventstore.com/server/v5/projections.html
  How it shold be related to this lib?
  View projections is out of scope for now.
2. Samples. You can find serveral examples in folders **example** and **example-tick-tack-toe-cqrx**

Project is not actively supported.
