### ISSUE TITLE
Publish event without adding to stream

### ISSUE THREAD

**Issue by justinpenguin45** [unlight/nestjs-cqrx#7]
Is there a way to publish an event from the aggregate without adding the event to the underlying aggregates stream? lets say I want to publish an integration event, or an event that I do not want stored in the aggregates stream? it seems currently not possible under the current architecture of the AggregateRoot? publishing is hardcoded to add to the event stream

**Comment by unlight** [comment]
Inject `EventStoreService` use `appendToStream` method

**Comment by unlight** [comment]
I think you need use `@nestjs/event-emitter` https://docs.nestjs.com/techniques/events
